# -*- coding: utf-8 -*-
"""asm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbn9jse_uUjojwbNSR7QdAqHLHuGQO2G
"""

import os
import csv
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

CSV_PATH = "/content/proptech_raw_dataset.csv"

if not os.path.exists(CSV_PATH):
    raise FileNotFoundError("Không tìm thấy file /content/proptech_raw_dataset.csv")

df = pd.read_csv(
    CSV_PATH,
    engine="python",
    on_bad_lines="skip",
    quoting=csv.QUOTE_MINIMAL,
    encoding_errors="ignore"
)

print("Đọc file CSV thành công")
print("Kích thước dữ liệu:", df.shape)
display(df.head())

print("\nThông tin dữ liệu:")
print(df.info())

print("\nThống kê dữ liệu số:")
display(df.describe(include=[np.number]).T)

print("\nThống kê dữ liệu object:")
display(df.describe(include=["object"]).T)

print("\nSố giá trị thiếu:")
missing_df = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_percent": df.isna().mean() * 100
}).sort_values("missing_percent", ascending=False)
display(missing_df)

print("Số dòng trùng lặp:", df.duplicated().sum())

num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
print("\nCác cột số:", num_cols)

for col in num_cols[:5]:
    plt.figure(figsize=(6,4))
    plt.hist(df[col].dropna(), bins=30)
    plt.title(f"Histogram - {col}")
    plt.xlabel(col)
    plt.ylabel("Frequency")
    plt.show()

for col in num_cols[:5]:
    plt.figure(figsize=(6,4))
    sns.boxplot(x=df[col])
    plt.title(f"Boxplot - {col}")
    plt.show()

for col in num_cols[:5]:
    plt.figure(figsize=(6,4))
    sns.violinplot(x=df[col])
    plt.title(f"Violin Plot - {col}")
    plt.show()

cat_cols = df.select_dtypes(include=["object"]).columns.tolist()
print("\nCác cột object:", cat_cols)

for col in cat_cols[:5]:
    print(f"\nTop 10 giá trị của cột {col}:")
    display(df[col].value_counts(dropna=False).head(10))