# -*- coding: utf-8 -*-
"""lab5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14gXVCSkQdNaRjbeDy2_hs4jlkg4VbWkD
"""

import pandas as pd
import numpy as np

# Đọc file dữ liệu
df = pd.read_csv('/content/ITA105_Slide_5.csv')

# Chuyển đổi cột date sang kiểu datetime
df['date'] = pd.to_datetime(df['date'])

# Xử lý giá trị thiếu (điền giá trị bằng phương pháp nội suy hoặc giá trị trước đó)
df['price'] = df['price'].fillna(method='ffill')


# Tạo các cột đặc trưng mới
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df['dayofweek'] = df['date'].dt.dayofweek

df['month_sin'] = np.sin(2 * np.pi * df['month']/12)
df['month_cos'] = np.cos(2 * np.pi * df['month']/12)