# -*- coding: utf-8 -*-
"""lab6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PCbeY95x0KbbyHvVT9BY3aNbvw8Ax-i6
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
import random

def process_image(img_path, task_type):
    # Đọc ảnh gốc
    img = cv2.imread(img_path)

    # Kiểm tra xem ảnh có được tải thành công không
    if img is None:
        print(f"Error: Could not load image from {img_path}. Please check the path.")
        return None, [] # Trả về giá trị rỗng hoặc xử lý lỗi tùy ý

    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # 1. Resize về 224x224 [cite: 6, 13, 20, 25]
    img_resized = cv2.resize(img, (224, 224))

    augmented_images = []

    # Định nghĩa các hàm Augmentation
    def rotate(image, angle):
        h, w = image.shape[:2]
        M = cv2.getRotationMatrix2D((w//2, h//2), angle, 1.0)
        return cv2.warpAffine(image, M, (w, h))

    def change_brightness(image, value):
        hsv = cv2.cvtColor(image, cv2.COLOR_RGB2HSV)
        v = hsv[:,:,2].astype(np.int16)
        v = np.clip(v + value, 0, 255)
        hsv[:,:,2] = v.astype(np.uint8)
        return cv2.cvtColor(hsv, cv2.COLOR_HSV2RGB)

    def add_gaussian_noise(image):
        row, col, ch = image.shape
        mean = 0
        var = 0.1
        sigma = var**0.5
        gauss = np.random.normal(mean, sigma, (row, col, ch)) * 255
        noisy = np.clip(image + gauss, 0, 255).astype(np.uint8)
        return noisy

    # 2. Thực hiện Augmentation theo từng bài
    if task_type == 1: # Bài 1: Căn hộ [cite: 5]
        for _ in range(5):
            temp = cv2.flip(img_resized, 1) # Horizontal flip [cite: 7]
            temp = rotate(temp, random.randint(-15, 15)) # Xoay +/- 15 độ [cite: 7]
            temp = change_brightness(temp, random.randint(-51, 51)) # Độ sáng +/- 20% (0.2*255 ~ 51) [cite: 8]
            # Chuyển Grayscale [cite: 9] và Chuẩn hóa [0, 1] [cite: 10]
            gray = cv2.cvtColor(temp, cv2.COLOR_RGB2GRAY)
            normalized = gray / 255.0
            augmented_images.append(normalized)

    elif task_type == 2: # Bài 2: Xe cộ [cite: 12]
        for _ in range(5):
            temp = add_gaussian_noise(img_resized) # Gaussian noise [cite: 14]
            temp = change_brightness(temp, random.randint(-38, 38)) # Độ sáng +/- 15% [cite: 14]
            temp = rotate(temp, random.randint(-10, 10)) # Xoay +/- 10 độ [cite: 15]
            normalized = temp / 255.0 # Chuẩn hóa [0, 1] [cite: 17, 18]
            augmented_images.append(normalized)

    elif task_type == 3: # Bài 3: Trái cây [cite: 19]
        for _ in range(9): # Grid 3x3 [cite: 23]
            temp = cv2.flip(img_resized, random.choice([-1, 0, 1])) # Flip [cite: 21]
            # Random Crop & Zoom giả lập bằng resize
            h, w = img_resized.shape[:2]
            start_x, start_y = random.randint(0, 20), random.randint(0, 20)
            crop = temp[start_y:h-start_y, start_x:w-x]
            temp = cv2.resize(crop, (224, 224))
            normalized = temp / 255.0 # Chuẩn hóa [0, 1] [cite: 22]
            augmented_images.append(normalized)

    return img_resized, augmented_images

# Ví dụ hiển thị Bài 1 (Bạn có thể thay đổi task_type từ 1-4)
# LƯU Ý: Thay thế 'path_to_your_image.jpg' bằng đường dẫn đến tệp ảnh của bạn
original, augmented = process_image('path_to_your_image.jpg', task_type=1)

# Chỉ hiển thị nếu ảnh được tải thành công
if original is not None:
    # Hiển thị kết quả
    plt.figure(figsize=(15, 5))
    plt.subplot(1, 6, 1)
    plt.title("Original")
    plt.imshow(original)
    plt.axis('off')

    for i in range(len(augmented[:5])):
        plt.subplot(1, 6, i+2)
        plt.title(f"Aug {i+1}")
        # Bài 1 & 4 yêu cầu Grayscale nên dùng cmap='gray' [cite: 9, 28]
        plt.imshow(augmented[i], cmap='gray' if augmented[i].ndim == 2 else None)
        plt.axis('off')

    plt.show()