# -*- coding: utf-8 -*-
"""lab8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PHtwymWGzzmZSS5E44wbqXTrt5wP-ns3
"""

"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EAGC7MIutFGdkZURf_uVskqXJy3vuJk7
"""


import pandas as pd
import numpy as np
import joblib
import matplotlib.pyplot as plt

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, PowerTransformer, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.model_selection import cross_val_score, KFold
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

df = pd.read_csv("ITA105_Lab_8.csv")

target = 'SalePrice'


for col in df.columns:
    try:
        df[col] = pd.to_numeric(df[col])
    except:
        pass

X = df.drop(columns=[target])
y = df[target]


numeric_cols = X.select_dtypes(include=np.number).columns.tolist()
categorical_cols = X.select_dtypes(include='object').columns.tolist()


class OutlierRemover(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        X = np.array(X, dtype=float)
        self.Q1 = np.percentile(X, 25, axis=0)
        self.Q3 = np.percentile(X, 75, axis=0)
        self.IQR = self.Q3 - self.Q1
        return self

    def transform(self, X):
        X = np.array(X, dtype=float)
        lower = self.Q1 - 1.5 * self.IQR
        upper = self.Q3 + 1.5 * self.IQR
        return np.clip(X, lower, upper)


print("\n===== BÀI 1: PIPELINE =====")

numeric_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('outlier', OutlierRemover()),
    ('scaler', StandardScaler()),
    ('power', PowerTransformer())
])

categorical_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])


preprocessor = ColumnTransformer([
    ('num', numeric_pipeline, numeric_cols),
    ('cat', categorical_pipeline, categorical_cols)
], sparse_threshold=0)

pipeline = Pipeline([
    ('preprocessor', preprocessor)
])

X_sample = X.head(10)
X_trans = pipeline.fit_transform(X_sample)

print("Shape sau pipeline:", X_trans.shape)


print("\n===== BÀI 2: TEST PIPELINE =====")

def create_test_cases(X):
    cases = {}

    cases['full'] = X.copy()


    X_missing = X.copy()
    X_missing.iloc[:5] = np.nan
    cases['missing'] = X_missing


    X_skew = X.copy()
    for col in numeric_cols:
        X_skew[col] = X_skew[col] ** 3
    cases['skew'] = X_skew


    X_unseen = X.copy()
    if categorical_cols:
        X_unseen[categorical_cols[0]] = "NEW_CATEGORY"
    cases['unseen'] = X_unseen


    X_wrong = X.copy()
    if numeric_cols:
        X_wrong[numeric_cols[0]] = "abc"
    cases['wrong_format'] = X_wrong

    return cases


cases = create_test_cases(X)

for name, data in cases.items():
    try:
        out = pipeline.fit_transform(data)
        print(f"{name}: OK - shape {out.shape}")
    except Exception as e:
        print(f"{name}: ERROR - {e}")



if len(numeric_cols) > 0:
    print("\nSo sánh phân phối...")

    col = numeric_cols[0]

    plt.hist(X[col], bins=30)
    plt.title("Before")
    plt.show()

    X_trans_full = pipeline.fit_transform(X)


    plt.hist(X_trans_full[:, 0], bins=30)
    plt.title("After")
    plt.show()


print("\n===== BÀI 3: MODEL + CV =====")

models = {
    "Linear": LinearRegression(),
    "RandomForest": RandomForestRegressor(n_estimators=100, random_state=42)
}

kf = KFold(n_splits=5, shuffle=True, random_state=42)

for name, model in models.items():
    full_model = Pipeline([
        ('preprocessor', preprocessor),
        ('model', model)
    ])

    scores = cross_val_score(full_model, X, y,
                             cv=kf,
                             scoring='neg_root_mean_squared_error')

    print(f"{name} RMSE:", -scores.mean())
    print(f"{name} STD:", scores.std())


print("\n===== BÀI 4: DEPLOY =====")


final_model = Pipeline([
    ('preprocessor', preprocessor),
    ('model', RandomForestRegressor(n_estimators=100, random_state=42))
])

final_model.fit(X, y)


joblib.dump(final_model, "house_price_model.pkl")
print("Đã lưu model!")

def predict_price(file_path):
    model = joblib.load("house_price_model.pkl")

    new_data = pd.read_csv(file_path)


    for col in new_data.columns:
        try:
            new_data[col] = pd.to_numeric(new_data[col])
        except:
            pass

    preds = model.predict(new_data)

    new_data['predicted_price'] = preds
    return new_data


print("\nTest dự đoán:")
print(predict_price("ITA105_Lab_8.csv").head())