# -*- coding: utf-8 -*-
"""lab 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mwMrYaAX3aUwlKmHFYCYVBhZ5Q6PvoMP
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Cấu hình hiển thị biểu đồ
plt.style.use('seaborn-v0_8')
sns.set_theme(style="whitegrid")

# =================================================================
# BÀI 1: KHÁM PHÁ VÀ TIỀN XỬ LÝ DỮ LIỆU (Ecommerce)
# =================================================================
print("--- ĐANG CHẠY BÀI 1: LÀM SẠCH DỮ LIỆU ECOMMERCE ---")
try:
    df_ecom = pd.read_csv('ITA105_Lab_2_Ecommerce.csv')

    # Xử lý dữ liệu thiếu và trùng lặp
    df_ecom_clean = df_ecom.dropna().drop_duplicates()

    print(f"Dữ liệu ban đầu: {df_ecom.shape}")
    print(f"Dữ liệu sau khi làm sạch: {df_ecom_clean.shape}")
    print("Hoàn thành Bài 1.\n")
except FileNotFoundError:
    print("Lỗi: Không tìm thấy file Ecommerce.csv\n")


# =================================================================
# BÀI 2: TÍNH TOÁN VÀ TRỰC QUAN HÓA DOANH THU (Ecommerce)
# =================================================================
print("--- ĐANG CHẠY BÀI 2: TRỰC QUAN HÓA DOANH THU ---")
try:
    # Tính Doanh thu = Số lượng * Đơn giá
    df_ecom_clean['Revenue'] = df_ecom_clean['quantity'] * df_ecom_clean['price']

    # Lấy Top 5 sản phẩm doanh thu cao nhất
    top_5 = df_ecom_clean.groupby('category')['Revenue'].sum().nlargest(5)

    plt.figure(figsize=(10, 5))
    top_5.plot(kind='bar', color='skyblue', edgecolor='black')
    plt.title('Top 5 Sản phẩm có Doanh thu cao nhất', fontsize=14)
    plt.ylabel('Doanh thu (USD)')
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show() # TẮT BIỂU ĐỒ NÀY ĐỂ CHẠY TIẾP BÀI 3
    print("Hoàn thành Bài 2.\n")
except NameError:
    print("Lỗi: Bài 1 chưa chạy thành công.\n")


# =================================================================
# BÀI 3: XỬ LÝ GIÁ TRỊ NGOẠI LAI (Housing)
# =================================================================
print("--- ĐANG CHẠY BÀI 3: LỌC OUTLIERS GIÁ NHÀ ---")
try:
    df_house = pd.read_csv('ITA105_Lab_2_Housing.csv')

    # Tính toán IQR để lọc Outliers cho cột gia
    Q1 = df_house['gia'].quantile(0.25)
    Q3 = df_house['gia'].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    # Lọc dữ liệu trong khoảng hợp lệ
    df_house_clean = df_house[(df_house['gia'] >= lower) & (df_house['gia'] <= upper)]

    # Trực quan hóa mối quan hệ Sqft và gia
    plt.figure(figsize=(10, 6))
    sns.scatterplot(data=df_house_clean, x='dien_tich', y='gia', hue='so_phong', palette='viridis')
    plt.title('Mối quan hệ Diện tích và Giá nhà (Sau khi lọc Outliers)', fontsize=14)
    plt.show() # TẮT BIỂU ĐỒ NÀY ĐỂ CHẠY TIẾP BÀI 4
    print(f"Đã loại bỏ {len(df_house) - len(df_house_clean)} dòng ngoại lai.")
    print("Hoàn thành Bài 3.\n")
except FileNotFoundError:
    print("Lỗi: Không tìm thấy file Housing.csv\n")


# =================================================================
# BÀI 4: LÀM MƯỢT DỮ LIỆU THỜI GIAN (IoT)
# =================================================================
print("--- ĐANG CHẠY BÀI 4: LÀM MƯỢT DỮ LIỆU NHIỆT ĐỘ IOT ---")
try:
    df_iot = pd.read_csv('ITA105_Lab_2_Iot.csv')

    # Chuyển Timestamp và làm mượt bằng Moving Average (window=5)
    df_iot['Timestamp'] = pd.to_datetime(df_iot['timestamp'])
    df_iot['Temp_Smooth'] = df_iot['temperature'].rolling(window=5, min_periods=1).mean()

    # Trực quan hóa dữ liệu
    plt.figure(figsize=(12, 6))
    plt.plot(df_iot['Timestamp'], df_iot['temperature'], label='Nhiệt độ gốc', alpha=0.3, color='gray')
    plt.plot(df_iot['Timestamp'], df_iot['Temp_Smooth'], label='Nhiệt độ làm mượt (MA-5)', color='red', linewidth=2)
    plt.title('Biến thiên Nhiệt độ IoT theo thời gian', fontsize=14)
    plt.legend()
    plt.xticks(rotation=30)
    plt.tight_layout()
    plt.show()
    print("Hoàn thành Bài 4.\n")
except FileNotFoundError:
    print("Lỗi: Không tìm thấy file Iot.csv\n")

print("--- CHÚC MỪNG HUNG ĐÃ HOÀN THÀNH TẤT CẢ BÀI TẬP LAB 2 ---")