# -*- coding: utf-8 -*-
"""lab 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X_7s5oFDP9YaWauWunfwlJ4sj3rGkzAN
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Cấu hình chung cho biểu đồ
sns.set(style="whitegrid")
plt.rcParams['figure.figsize'] = (15, 6)

# =================================================================
# BÀI 1: THÔNG SỐ VẬN ĐỘNG VIÊN (ITA105_Lab_3_Sports.csv)
# Mục tiêu: Chuẩn hóa dữ liệu về chiều cao, cân nặng, tốc độ...
# =================================================================
print("--- ĐANG XỬ LÝ BÀI 1: SPORTS ---")
df1 = pd.read_csv('ITA105_Lab_3_Sports.csv')

# 1.1 Thống kê và kiểm tra
print(df1.describe())

# 1.2 Thực hiện chuẩn hóa
scaler_mm = MinMaxScaler()
scaler_std = StandardScaler()

df1_minmax = pd.DataFrame(scaler_mm.fit_transform(df1), columns=df1.columns)
df1_zscore = pd.DataFrame(scaler_std.fit_transform(df1), columns=df1.columns)

# 1.3 Vẽ biểu đồ so sánh phân phối (Histogram)
fig, axes = plt.subplots(1, 3)
sns.histplot(df1['toc_do_100m_s'], kde=True, ax=axes[0]).set_title('Gốc (Tốc độ)')
sns.histplot(df1_minmax['toc_do_100m_s'], kde=True, ax=axes[1]).set_title('Min-Max (0-1)')
sns.histplot(df1_zscore['toc_do_100m_s'], kde=True, ax=axes[2]).set_title('Z-Score (Mean=0)')
plt.suptitle('BÀI 1: SO SÁNH CÁC PHƯƠNG PHÁP CHUẨN HÓA')
plt.show()


# =================================================================
# BÀI 2: CHỈ SỐ BỆNH NHÂN (ITA105_Lab_3_Health.csv)
# Mục tiêu: Phát hiện Outliers (ngoại lệ) trong y tế
# =================================================================
print("\n--- ĐANG XỬ LÝ BÀI 2: HEALTH ---")
df2 = pd.read_csv('ITA105_Lab_3_Health.csv')

# 2.1 Vẽ Boxplot để tìm ngoại lệ
plt.figure(figsize=(10, 5))
sns.boxplot(data=df2)
plt.title("BÀI 2: PHÁT HIỆN NGOẠI LỆ (OUTLIERS) TRONG CHỈ SỐ SỨC KHỎE")
plt.show()

# 2.2 Chuẩn hóa Z-Score (Thường dùng khi có nhiều Outliers)
df2_zscore = pd.DataFrame(scaler_std.fit_transform(df2), columns=df2.columns)
print("Dữ liệu sau khi chuẩn hóa Z-Score (5 dòng đầu):")
print(df2_zscore.head())


# =================================================================
# BÀI 3: CHỈ SỐ CÔNG TY (ITA105_Lab_3_Finance.csv)
# Mục tiêu: So sánh sự tương quan giữa Doanh thu và Lợi nhuận
# =================================================================
print("\n--- ĐANG XỬ LÝ BÀI 3: FINANCE ---")
df3 = pd.read_csv('ITA105_Lab_3_Finance.csv')

# 3.1 Chuẩn hóa dữ liệu
df3_zscore = pd.DataFrame(scaler_std.fit_transform(df3), columns=df3.columns)

# 3.2 Vẽ Scatter Plot so sánh trước và sau chuẩn hóa
fig, (ax1, ax2) = plt.subplots(1, 2)

sns.scatterplot(data=df3, x='doanh_thu_musd', y='loi_nhuan_musd', ax=ax1)
ax1.set_title("Gốc: Doanh thu vs Lợi nhuận")

sns.scatterplot(data=df3_zscore, x='doanh_thu_musd', y='loi_nhuan_musd', ax=ax2, color='orange')
ax2.set_title("Sau Z-Score: Doanh thu vs Lợi nhuận")

plt.suptitle('BÀI 3: TƯƠNG QUAN TÀI CHÍNH')
plt.show()


# =================================================================
# BÀI 4: NGƯỜI CHƠI TRỰC TUYẾN (ITA105_Lab_3_Gaming.csv)
# Mục tiêu: Đưa các chỉ số giờ chơi, level về cùng thang đo
# =================================================================
print("\n--- ĐANG XỬ LÝ BÀI 4: GAMING ---")
df4 = pd.read_csv('ITA105_Lab_3_Gaming.csv')

# 4.1 Chuẩn hóa Min-Max (Để so sánh các chỉ số trên thang [0, 1])
df4_minmax = pd.DataFrame(scaler_mm.fit_transform(df4), columns=df4.columns)

# 4.2 Vẽ biểu đồ Boxplot so sánh thang đo
fig, (ax1, ax2) = plt.subplots(1, 2)
sns.boxplot(data=df4, ax=ax1).set_title("Trước chuẩn hóa (Thang đo lệch nhau)")
sns.boxplot(data=df4_minmax, ax=ax2).set_title("Sau Min-Max (Cùng thang đo 0-1)")
plt.show()

print("--- HOÀN THÀNH TẤT CẢ CÁC BÀI LAB 3 ---")