# -*- coding: utf-8 -*-
"""lab 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5XfIuf6VnvJcLLadiQwyxMtKVR5IdCi
"""

"""lab7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w4Ukbpl8Sx3xvYPP3MCubwqewJbjReMj
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PowerTransformer
from sklearn.metrics import mean_squared_error, r2_score

df = pd.read_csv('ITA105_Lab_7.csv')

sns.set(style="whitegrid")

# =================================================================
# BÀI 1: PHÂN TÍCH DỮ LIỆU & KHÁM PHÁ PHÂN PHỐI (2đ)
# =================================================================
print("--- BÀI 1 ---")
numeric_cols = df.select_dtypes(include=[np.number]).columns
skewness = df[numeric_cols].skew().sort_values(ascending=False)
print("Top các cột lệch nhất:\n", skewness)

top_3_skew = skewness.index[:2].tolist() + [skewness.index[-1]]
plt.figure(figsize=(18, 5))
for i, col in enumerate(top_3_skew):
    plt.subplot(1, 3, i+1)
    sns.histplot(df[col], kde=True, color='teal')
    plt.title(f"Phân phối {col}\nSkewness: {df[col].skew():.2f}")
plt.show()


# =================================================================
# BÀI 2: BIẾN ĐỔI DỮ LIỆU NÂNG CAO (2đ)
# =================================================================
print("\n--- BÀI 2 ---")

df['SalePrice_Log'] = np.log1p(df['SalePrice'])

df['LotArea_BoxCox'], lmbda = stats.boxcox(df['LotArea'])
print(f"Lambda (λ) tối ưu của Box-Cox cho LotArea: {lmbda:.4f}")

yj_transformer = PowerTransformer(method='yeo-johnson')
df['NegSkewIncome_YJ'] = yj_transformer.fit_transform(df[['NegSkewIncome']])

comparison = pd.DataFrame({
    'Cột': ['SalePrice', 'LotArea', 'NegSkewIncome'],
    'Skew Gốc': [df['SalePrice'].skew(), df['LotArea'].skew(), df['NegSkewIncome'].skew()],
    'Sau Log': [df['SalePrice_Log'].skew(), np.nan, np.nan],
    'Sau Box-Cox': [np.nan, df['LotArea_BoxCox'].skew(), np.nan],
    'Sau Power (YJ)': [np.nan, np.nan, df['NegSkewIncome_YJ'].skew()]
})
print(comparison)

# =================================================================
# BÀI 3: ỨNG DỤNG VÀO MÔ HÌNH HÓA (2đ)
# =================================================================
print("\n--- BÀI 3 ---")

def run_regression(X, y, is_log_y=False):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    model = LinearRegression()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    if is_log_y:
        y_test_actual = np.expm1(y_test)
        y_pred_actual = np.expm1(y_pred)
        rmse = np.sqrt(mean_squared_error(y_test_actual, y_pred_actual))
    else:
        rmse = np.sqrt(mean_squared_error(y_test, y_pred))

    r2 = r2_score(y_test, y_pred)
    return rmse, r2

features_raw = ['LotArea', 'HouseAge', 'Rooms']
rmse_a, r2_a = run_regression(df[features_raw], df['SalePrice'])

rmse_b, r2_b = run_regression(df[features_raw], df['SalePrice_Log'], is_log_y=True)

features_transformed = ['LotArea_BoxCox', 'HouseAge', 'Rooms']
rmse_c, r2_c = run_regression(df[features_transformed], df['SalePrice_Log'], is_log_y=True)

print(f"Version A (Gốc): RMSE = {rmse_a:,.2f}, R2 = {r2_a:.4f}")
print(f"Version B (Log Target): RMSE = {rmse_b:,.2f}, R2 = {r2_b:.4f}")
print(f"Version C (Transformed): RMSE = {rmse_c:,.2f}, R2 = {r2_c:.4f}")

# =================================================================
# BÀI 4: ỨNG DỤNG NGHIỆP VỤ & RA QUYẾT ĐỊNH (2đ)
# =================================================================
print("\n--- BÀI 4: Trực quan hóa cho Insight ---")

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

sns.histplot(df['LotArea'], ax=axes[0], color='orange', kde=True)
axes[0].set_title("Version A: Dữ liệu Raw (LotArea)")
axes[0].set_xlabel("Diện tích (Dữ liệu bị nén ở một bên)")

sns.histplot(df['LotArea_BoxCox'], ax=axes[1], color='green', kde=True)
axes[1].set_title("Version B: Dữ liệu Transform (Box-Cox)")
axes[1].set_xlabel("Diện tích (Phân bổ chuẩn, dễ quan sát)")

plt.show()